---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: 12.19.36

provisioner:
  name: chef_zero


verifier:
  name: inspec

platforms:
  - name: centos-6.9

suites:
  - name: default
    run_list:
      - recipe[gl_chef_server]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
